# syntax:
# action = 'key'
# action = ['key1', 'key2']
quit = ['q', 'Q']
go = 'enter'
up = 'up'
down = 'down'
rew = 'left'
ff = 'right'
pgup = 'pgup'
pgdown = 'pgdown'
home = 'home'
end = 'end'
stop = 's'
next = 'n'
prev = 'b'
pause = [' ', 'p']
toggle = 'tab'
add_to_playlist = ['a', 'A']
toggle_progress = 'P'
toggle_shuffle = 'S'
toggle_repeat = 'R'
toggle_next = ['N', 'X']
lyrics = 'L'
help = ['?', 'h']
delete = 'd'
clear = 'C'
reset_view = '^x'
