name: pmcp build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get update -q
          sudo apt-get install -y g++-13 meson ninja-build libcpptoml-dev libpipewire-0.3-dev libsndfile1-dev libtag1-dev libglyr-dev
        shell: bash

      - name: Configure and build the app
        run: |
          meson build
          ninja -C build
        env:
          CXX: g++-13
